name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - name: Package Extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
            extensionDir: './dist'
            zipFilePath: 'dist.zip'
            zipIgnore: '*.pem|.git|*.crx|.github|sidebar|_metadata|screenshot.png'
      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: dist.zip
          crxFilePath: bundle-replacer-${{ github.ref_name }}.crx
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
      - run: bun run scripts/build-update.ts ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist.zip
            bundle-replacer-${{ github.ref_name }}.crx
            updates.xml
permissions:
  contents: write
